// packages/examples/example-react/src/App.jsx
/**
 * To showcase the usage of the dnb-ui-lib in React
 *
 */

import React, { Component, Fragment } from 'react'
import './App.css'

// different mothodes of importing the dnb-ui-lib
// import Icon from 'dnb-ui-lib/components/icon' // alternative method to import dnb-ui-lib
// import Button from 'dnb-ui-lib/components/Button' // alternative method to import dnb-ui-lib
// import dnb from 'dnb-ui-lib/components' // alternative method to import dnb-ui-lib
// import 'dnb-ui-lib/components/Button/style' // Import only the button styles
// import 'dnb-ui-lib/components/Icon/style' // Import only the icon styles
// import 'dnb-ui-lib/components' // in case we only use web component version

import dnb, { Button, Input, Icon } from 'dnb-ui-lib/components' // optional, import "dnb-ui-lib/components/web-components" to enable Web Components
import { bell } from 'dnb-ui-lib/components/icon/lib'
import 'dnb-ui-lib/style' // Import the global DNB stylesheet

// to enable Web Components, cause we use both react and Web Components in here

export default class App extends Component {
  state = { showWebComponents: false }
  constructor(props) {
    super(props)
    this._buttonRef = React.createRef()
    this._inputRef = React.createRef()
  }
  handleClick = e => {
    console.log('handleClick', e)
  }
  handleValueChange = e => {
    console.log(
      'handleValueChange',
      e.value || (e.detail && e.detail.value) || ''
    )
  }
  handleWebComponentsVisibility() {
    this.setState({ showWebComponents: true })
    dnb.enableWebComponents()

    // there are different ways to enable usage of WebComponents
    // Button.enableWebComponents()
    // Icon.enableWebComponents()
    //
    // bind the imperative (not declarative) event handlers
    this._inputRef.current.addEvent('on_change', this.handleValueChange)
    this._buttonRef.current.addEvent('on_click', this.handleClick)
  }
  componentDidMount() {
    setTimeout(this.handleWebComponentsVisibility.bind(this), 100)
  }
  render() {
    return (
      <div>
        <h1>React Components</h1>
        <Input
          placeholder="Type someting ..."
          on_change={this.handleValueChange}
        />
        <Button
          text="Custom Element with icon"
          icon="chevron-right"
          on_click={this.handleClick}
        />
        <Icon icon={bell} width={80} />
        {this.state.showWebComponents && (
          <Fragment>
            <h1>Web Component in React</h1>
            <small>
              This is not for real world usage. But only to show the
              functionality of the dnb-ui-lib
            </small>
            <dnb-input
              ref={this._inputRef}
              placeholder="Type someting ..."
              on_change={e => {
                console.log('e', e)
              }}
            />
            <dnb-button
              ref={this._buttonRef}
              text="Custom Element with icon"
              icon="chevron-right"
              on_click={this.handleClick}
            />
            <dnb-icon icon="bell" size="80" />
          </Fragment>
        )}
      </div>
    )
  }
}

// packages/examples/example-vue/src/App.vue
<template lang="html">
  <div id="app" class="dnb-style">
    <h1>{{ header }}</h1>
    <dnb-button :text="header" @on_click="onClick"></dnb-button>
    <dnb-input @on_change="onChange" value="My Input Value" placeholder="My Placeholder"></dnb-input>

    <!-- <dnb-button
      ref="button"
      text="Custom Element with icon"
      icon="chevron-right"
      @click="handleClick"
      v-on:click="onClick"
    ></dnb-button>
    <dnb-icon-with-all-icons
      icon="bell"
      size="80"
    ></dnb-icon-with-all-icons>
    <dnb-input
      ref="input"
      placeholder="Type someting ..."
    ></dnb-input> -->

  </div>
</template>

<script>
import Vue from 'vue'

// You have to choose to wehter use web-components or vuera (React) components
/* Import dnb from 'dnb-ui-lib/components/web-components' // optional, import "dnb-ui-lib/components/web-components" to enable Web Components */

/* import 'dnb-ui-lib/style' // Import the global DNB stylesheet */
/* import 'dnb-ui-lib/components/style' // Import all components */

import 'dnb-ui-lib/components/button/style'
import 'dnb-ui-lib/components/input/style'
import 'dnb-ui-lib/style/theme'
import dnb, { Button, Input } from 'dnb-ui-lib/components/vue'

const components = dnb.getComponents(Vue)

// Make sure we add Vue to the config to add all ignoredElements
// In case we use web-components
/* dnb.setIgnoredPatterns(Vue) */

export default {
  name: 'app',
  data: () => ({
    header: 'React Components in Vue'
    /* header: 'Web Components in Vue' */
  }),
  methods: {
    onClick: function(e) {
      console.log('onClick', e)
    },
    handleClick: e => {
      console.log('handleClick', e)
    },
    onChange: e => {
      console.log('onChange', e.value || (e.target && e.target.value))
    },
    handleChange: e => {
      console.log('handleChange', e.value || (e.target && e.target.value))
    }
  },
  // only a use case if we use web-components
  /* mounted() {
    this.$refs.button.addEvent('on_click', this.handleClick)
    this.$refs.input.addEvent('on_change', this.handleChange)
  }, */
  components
}
</script>

<style lang="css">
  html,
  body {
    height: 100%;
  }
  body {
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Helvetica, Arial,
    sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol';
  }
  div.center {
    display: flex;
    justify-content: center;
    align-items: center;
  }
  h1 {
    font-weight: 300;
  }
</style>
